<?php

use App\Models\User;
use Illuminate\Support\Collection;

function user(): ?User
{
    return auth()->user();
}

function money($value, $currency = 'USD'): string
{
    $fmt = new NumberFormatter('en_US', NumberFormatter::CURRENCY);

    return $fmt->formatCurrency($value, $currency);
}

function countries(): Collection
{
    return collect([
        (object) ['code' => 'AF', 'name' => 'Afghanistan'],
        (object) ['code' => 'AL', 'name' => 'Albania'],
        (object) ['code' => 'DZ', 'name' => 'Algeria'],
        (object) ['code' => 'AS', 'name' => 'American Samoa'],
        (object) ['code' => 'AD', 'name' => 'Andorra'],
        (object) ['code' => 'AO', 'name' => 'Angola'],
        (object) ['code' => 'AI', 'name' => 'Anguilla'],
        (object) ['code' => 'AQ', 'name' => 'Antarctica'],
        (object) ['code' => 'AG', 'name' => 'Antigua and Barbuda'],
        (object) ['code' => 'AR', 'name' => 'Argentina'],
        (object) ['code' => 'AM', 'name' => 'Armenia'],
        (object) ['code' => 'AW', 'name' => 'Aruba'],
        (object) ['code' => 'AU', 'name' => 'Australia'],
        (object) ['code' => 'AT', 'name' => 'Austria'],
        (object) ['code' => 'AZ', 'name' => 'Azerbaijan'],
        (object) ['code' => 'BS', 'name' => 'Bahamas'],
        (object) ['code' => 'BH', 'name' => 'Bahrain'],
        (object) ['code' => 'BD', 'name' => 'Bangladesh'],
        (object) ['code' => 'BB', 'name' => 'Barbados'],
        (object) ['code' => 'BY', 'name' => 'Belarus'],
        (object) ['code' => 'BE', 'name' => 'Belgium'],
        (object) ['code' => 'BZ', 'name' => 'Belize'],
        (object) ['code' => 'BJ', 'name' => 'Benin'],
        (object) ['code' => 'BM', 'name' => 'Bermuda'],
        (object) ['code' => 'BT', 'name' => 'Bhutan'],
        (object) ['code' => 'BO', 'name' => 'Bolivia'],
        (object) ['code' => 'BA', 'name' => 'Bosnia and Herzegovina'],
        (object) ['code' => 'BW', 'name' => 'Botswana'],
        (object) ['code' => 'BV', 'name' => 'Bouvet Island'],
        (object) ['code' => 'BR', 'name' => 'Brazil'],
        (object) ['code' => 'IO', 'name' => 'British Indian Ocean Territory'],
        (object) ['code' => 'BN', 'name' => 'Brunei Darussalam'],
        (object) ['code' => 'BG', 'name' => 'Bulgaria'],
        (object) ['code' => 'BF', 'name' => 'Burkina Faso'],
        (object) ['code' => 'BI', 'name' => 'Burundi'],
        (object) ['code' => 'KH', 'name' => 'Cambodia'],
        (object) ['code' => 'CM', 'name' => 'Cameroon'],
        (object) ['code' => 'CA', 'name' => 'Canada'],
        (object) ['code' => 'CV', 'name' => 'Cape Verde'],
        (object) ['code' => 'KY', 'name' => 'Cayman Islands'],
        (object) ['code' => 'CF', 'name' => 'Central African Republic'],
        (object) ['code' => 'TD', 'name' => 'Chad'],
        (object) ['code' => 'CL', 'name' => 'Chile'],
        (object) ['code' => 'CN', 'name' => 'China'],
        (object) ['code' => 'CX', 'name' => 'Christmas Island'],
        (object) ['code' => 'CC', 'name' => 'Cocos (Keeling) Islands'],
        (object) ['code' => 'CO', 'name' => 'Colombia'],
        (object) ['code' => 'KM', 'name' => 'Comoros'],
        (object) ['code' => 'CG', 'name' => 'Congo'],
        (object) ['code' => 'CD', 'name' => 'Congo, the Democratic Republic of the'],
        (object) ['code' => 'CK', 'name' => 'Cook Islands'],
        (object) ['code' => 'CR', 'name' => 'Costa Rica'],
        (object) ['code' => 'CI', 'name' => "Cote D'Ivoire"],
        (object) ['code' => 'HR', 'name' => 'Croatia'],
        (object) ['code' => 'CU', 'name' => 'Cuba'],
        (object) ['code' => 'CY', 'name' => 'Cyprus'],
        (object) ['code' => 'CZ', 'name' => 'Czech Republic'],
        (object) ['code' => 'DK', 'name' => 'Denmark'],
        (object) ['code' => 'DJ', 'name' => 'Djibouti'],
        (object) ['code' => 'DM', 'name' => 'Dominica'],
        (object) ['code' => 'DO', 'name' => 'Dominican Republic'],
        (object) ['code' => 'EC', 'name' => 'Ecuador'],
        (object) ['code' => 'EG', 'name' => 'Egypt'],
        (object) ['code' => 'SV', 'name' => 'El Salvador'],
        (object) ['code' => 'GQ', 'name' => 'Equatorial Guinea'],
        (object) ['code' => 'ER', 'name' => 'Eritrea'],
        (object) ['code' => 'EE', 'name' => 'Estonia'],
        (object) ['code' => 'ET', 'name' => 'Ethiopia'],
        (object) ['code' => 'FK', 'name' => 'Falkland Islands (Malvinas)'],
        (object) ['code' => 'FO', 'name' => 'Faroe Islands'],
        (object) ['code' => 'FJ', 'name' => 'Fiji'],
        (object) ['code' => 'FI', 'name' => 'Finland'],
        (object) ['code' => 'FR', 'name' => 'France'],
        (object) ['code' => 'GF', 'name' => 'French Guiana'],
        (object) ['code' => 'PF', 'name' => 'French Polynesia'],
        (object) ['code' => 'TF', 'name' => 'French Southern Territories'],
        (object) ['code' => 'GA', 'name' => 'Gabon'],
        (object) ['code' => 'GM', 'name' => 'Gambia'],
        (object) ['code' => 'GE', 'name' => 'Georgia'],
        (object) ['code' => 'DE', 'name' => 'Germany'],
        (object) ['code' => 'GH', 'name' => 'Ghana'],
        (object) ['code' => 'GI', 'name' => 'Gibraltar'],
        (object) ['code' => 'GR', 'name' => 'Greece'],
        (object) ['code' => 'GL', 'name' => 'Greenland'],
        (object) ['code' => 'GD', 'name' => 'Grenada'],
        (object) ['code' => 'GP', 'name' => 'Guadeloupe'],
        (object) ['code' => 'GU', 'name' => 'Guam'],
        (object) ['code' => 'GT', 'name' => 'Guatemala'],
        (object) ['code' => 'GN', 'name' => 'Guinea'],
        (object) ['code' => 'GW', 'name' => 'Guinea-Bissau'],
        (object) ['code' => 'GY', 'name' => 'Guyana'],
        (object) ['code' => 'HT', 'name' => 'Haiti'],
        (object) ['code' => 'HM', 'name' => 'Heard Island and Mcdonald Islands'],
        (object) ['code' => 'VA', 'name' => 'Holy See (Vatican City State)'],
        (object) ['code' => 'HN', 'name' => 'Honduras'],
        (object) ['code' => 'HK', 'name' => 'Hong Kong'],
        (object) ['code' => 'HU', 'name' => 'Hungary'],
        (object) ['code' => 'IS', 'name' => 'Iceland'],
        (object) ['code' => 'IN', 'name' => 'India'],
        (object) ['code' => 'ID', 'name' => 'Indonesia'],
        (object) ['code' => 'IR', 'name' => 'Iran, Islamic Republic of'],
        (object) ['code' => 'IQ', 'name' => 'Iraq'],
        (object) ['code' => 'IE', 'name' => 'Ireland'],
        (object) ['code' => 'IL', 'name' => 'Israel'],
        (object) ['code' => 'IT', 'name' => 'Italy'],
        (object) ['code' => 'JM', 'name' => 'Jamaica'],
        (object) ['code' => 'JP', 'name' => 'Japan'],
        (object) ['code' => 'JO', 'name' => 'Jordan'],
        (object) ['code' => 'KZ', 'name' => 'Kazakhstan'],
        (object) ['code' => 'KE', 'name' => 'Kenya'],
        (object) ['code' => 'KI', 'name' => 'Kiribati'],
        (object) ['code' => 'KP', 'name' => "Korea, Democratic People's Republic of"],
        (object) ['code' => 'KR', 'name' => 'Korea, Republic of'],
        (object) ['code' => 'KW', 'name' => 'Kuwait'],
        (object) ['code' => 'KG', 'name' => 'Kyrgyzstan'],
        (object) ['code' => 'LA', 'name' => "Lao People's Democratic Republic"],
        (object) ['code' => 'LV', 'name' => 'Latvia'],
        (object) ['code' => 'LB', 'name' => 'Lebanon'],
        (object) ['code' => 'LS', 'name' => 'Lesotho'],
        (object) ['code' => 'LR', 'name' => 'Liberia'],
        (object) ['code' => 'LY', 'name' => 'Libyan Arab Jamahiriya'],
        (object) ['code' => 'LI', 'name' => 'Liechtenstein'],
        (object) ['code' => 'LT', 'name' => 'Lithuania'],
        (object) ['code' => 'LU', 'name' => 'Luxembourg'],
        (object) ['code' => 'MO', 'name' => 'Macao'],
        (object) ['code' => 'MK', 'name' => 'Macedonia, the Former Yugoslav Republic of'],
        (object) ['code' => 'MG', 'name' => 'Madagascar'],
        (object) ['code' => 'MW', 'name' => 'Malawi'],
        (object) ['code' => 'MY', 'name' => 'Malaysia'],
        (object) ['code' => 'MV', 'name' => 'Maldives'],
        (object) ['code' => 'ML', 'name' => 'Mali'],
        (object) ['code' => 'MT', 'name' => 'Malta'],
        (object) ['code' => 'MH', 'name' => 'Marshall Islands'],
        (object) ['code' => 'MQ', 'name' => 'Martinique'],
        (object) ['code' => 'MR', 'name' => 'Mauritania'],
        (object) ['code' => 'MU', 'name' => 'Mauritius'],
        (object) ['code' => 'YT', 'name' => 'Mayotte'],
        (object) ['code' => 'MX', 'name' => 'Mexico'],
        (object) ['code' => 'FM', 'name' => 'Micronesia, Federated States of'],
        (object) ['code' => 'MD', 'name' => 'Moldova, Republic of'],
        (object) ['code' => 'MC', 'name' => 'Monaco'],
        (object) ['code' => 'MN', 'name' => 'Mongolia'],
        (object) ['code' => 'MS', 'name' => 'Montserrat'],
        (object) ['code' => 'MA', 'name' => 'Morocco'],
        (object) ['code' => 'MZ', 'name' => 'Mozambique'],
        (object) ['code' => 'MM', 'name' => 'Myanmar'],
        (object) ['code' => 'NA', 'name' => 'Namibia'],
        (object) ['code' => 'NR', 'name' => 'Nauru'],
        (object) ['code' => 'NP', 'name' => 'Nepal'],
        (object) ['code' => 'NL', 'name' => 'Netherlands'],
        (object) ['code' => 'AN', 'name' => 'Netherlands Antilles'],
        (object) ['code' => 'NC', 'name' => 'New Caledonia'],
        (object) ['code' => 'NZ', 'name' => 'New Zealand'],
        (object) ['code' => 'NI', 'name' => 'Nicaragua'],
        (object) ['code' => 'NE', 'name' => 'Niger'],
        (object) ['code' => 'NG', 'name' => 'Nigeria'],
        (object) ['code' => 'NU', 'name' => 'Niue'],
        (object) ['code' => 'NF', 'name' => 'Norfolk Island'],
        (object) ['code' => 'MP', 'name' => 'Northern Mariana Islands'],
        (object) ['code' => 'NO', 'name' => 'Norway'],
        (object) ['code' => 'OM', 'name' => 'Oman'],
        (object) ['code' => 'PK', 'name' => 'Pakistan'],
        (object) ['code' => 'PW', 'name' => 'Palau'],
        (object) ['code' => 'PS', 'name' => 'Palestinian Territory, Occupied'],
        (object) ['code' => 'PA', 'name' => 'Panama'],
        (object) ['code' => 'PG', 'name' => 'Papua New Guinea'],
        (object) ['code' => 'PY', 'name' => 'Paraguay'],
        (object) ['code' => 'PE', 'name' => 'Peru'],
        (object) ['code' => 'PH', 'name' => 'Philippines'],
        (object) ['code' => 'PN', 'name' => 'Pitcairn'],
        (object) ['code' => 'PL', 'name' => 'Poland'],
        (object) ['code' => 'PT', 'name' => 'Portugal'],
        (object) ['code' => 'PR', 'name' => 'Puerto Rico'],
        (object) ['code' => 'QA', 'name' => 'Qatar'],
        (object) ['code' => 'RE', 'name' => 'Reunion'],
        (object) ['code' => 'RO', 'name' => 'Romania'],
        (object) ['code' => 'RU', 'name' => 'Russian Federation'],
        (object) ['code' => 'RW', 'name' => 'Rwanda'],
        (object) ['code' => 'SH', 'name' => 'Saint Helena'],
        (object) ['code' => 'KN', 'name' => 'Saint Kitts and Nevis'],
        (object) ['code' => 'LC', 'name' => 'Saint Lucia'],
        (object) ['code' => 'PM', 'name' => 'Saint Pierre and Miquelon'],
        (object) ['code' => 'VC', 'name' => 'Saint Vincent and the Grenadines'],
        (object) ['code' => 'WS', 'name' => 'Samoa'],
        (object) ['code' => 'SM', 'name' => 'San Marino'],
        (object) ['code' => 'ST', 'name' => 'Sao Tome and Principe'],
        (object) ['code' => 'SA', 'name' => 'Saudi Arabia'],
        (object) ['code' => 'SN', 'name' => 'Senegal'],
        (object) ['code' => 'CS', 'name' => 'Serbia and Montenegro'],
        (object) ['code' => 'SC', 'name' => 'Seychelles'],
        (object) ['code' => 'SL', 'name' => 'Sierra Leone'],
        (object) ['code' => 'SG', 'name' => 'Singapore'],
        (object) ['code' => 'SK', 'name' => 'Slovakia'],
        (object) ['code' => 'SI', 'name' => 'Slovenia'],
        (object) ['code' => 'SB', 'name' => 'Solomon Islands'],
        (object) ['code' => 'SO', 'name' => 'Somalia'],
        (object) ['code' => 'ZA', 'name' => 'South Africa'],
        (object) ['code' => 'GS', 'name' => 'South Georgia and the South Sandwich Islands'],
        (object) ['code' => 'ES', 'name' => 'Spain'],
        (object) ['code' => 'LK', 'name' => 'Sri Lanka'],
        (object) ['code' => 'SD', 'name' => 'Sudan'],
        (object) ['code' => 'SR', 'name' => 'Suriname'],
        (object) ['code' => 'SJ', 'name' => 'Svalbard and Jan Mayen'],
        (object) ['code' => 'SZ', 'name' => 'Swaziland'],
        (object) ['code' => 'SE', 'name' => 'Sweden'],
        (object) ['code' => 'CH', 'name' => 'Switzerland'],
        (object) ['code' => 'SY', 'name' => 'Syrian Arab Republic'],
        (object) ['code' => 'TW', 'name' => 'Taiwan, Province of China'],
        (object) ['code' => 'TJ', 'name' => 'Tajikistan'],
        (object) ['code' => 'TZ', 'name' => 'Tanzania, United Republic of'],
        (object) ['code' => 'TH', 'name' => 'Thailand'],
        (object) ['code' => 'TL', 'name' => 'Timor-Leste'],
        (object) ['code' => 'TG', 'name' => 'Togo'],
        (object) ['code' => 'TK', 'name' => 'Tokelau'],
        (object) ['code' => 'TO', 'name' => 'Tonga'],
        (object) ['code' => 'TT', 'name' => 'Trinidad and Tobago'],
        (object) ['code' => 'TN', 'name' => 'Tunisia'],
        (object) ['code' => 'TR', 'name' => 'Turkey'],
        (object) ['code' => 'TM', 'name' => 'Turkmenistan'],
        (object) ['code' => 'TC', 'name' => 'Turks and Caicos Islands'],
        (object) ['code' => 'TV', 'name' => 'Tuvalu'],
        (object) ['code' => 'UG', 'name' => 'Uganda'],
        (object) ['code' => 'UA', 'name' => 'Ukraine'],
        (object) ['code' => 'AE', 'name' => 'United Arab Emirates'],
        (object) ['code' => 'GB', 'name' => 'United Kingdom'],
        (object) ['code' => 'US', 'name' => 'United States'],
        (object) ['code' => 'UM', 'name' => 'United States Minor Outlying Islands'],
        (object) ['code' => 'UY', 'name' => 'Uruguay'],
        (object) ['code' => 'UZ', 'name' => 'Uzbekistan'],
        (object) ['code' => 'VU', 'name' => 'Vanuatu'],
        (object) ['code' => 'VE', 'name' => 'Venezuela'],
        (object) ['code' => 'VN', 'name' => 'Viet Nam'],
        (object) ['code' => 'VG', 'name' => 'Virgin Islands, British'],
        (object) ['code' => 'VI', 'name' => 'Virgin Islands, U.s.'],
        (object) ['code' => 'WF', 'name' => 'Wallis and Futuna'],
        (object) ['code' => 'EH', 'name' => 'Western Sahara'],
        (object) ['code' => 'YE', 'name' => 'Yemen'],
        (object) ['code' => 'ZM', 'name' => 'Zambia'],
        (object) ['code' => 'ZW', 'name' => 'Zimbabwe'],
    ]);
}
